### ISSUE TITLE
Running `./bin/satis build` in newly cloned directory causes PHP Fatal error.

### ISSUE THREAD

**Issue by circuuz** [composer/satis#573]
**Describe the bug**
Running `./bin/satis build` causes the following error.

```
Fatal error: Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found in
```

**To Reproduce**

1. `git clone`
2. `composer install`
3. `./bin/satis build`

**Outcome**

```
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Process\ProcessBuilder' not found in /Users/XXX/.composer/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php:118
Stack trace:
#0 /Users/XXX/.composer/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php(103): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->init()
#1 /Users/XXX/dev/satis/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(237): Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\NullIO))
#2 /Users/XXX/dev/satis/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(206): Composer\Plugin\PluginManager->addPlugin(Object(Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin))
#3 /Users/XXX/dev/satis/vendor/composer/composer/src/Composer/Plugin/PluginManager.php(264): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#4 /Users/XXX/d in /Users/XXX/.composer/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php on line 118
```

**Expected behavior**
I expect the repository to be built.

**Additional context**
ProcessBuilder was deprecated in symfony/component 3.4.0 and removed in symfony/component 4.0
see https://github.com/symfony/process/blob/master/CHANGELOG.md

**Comment by alcohol** [comment]
The error is thrown inside a plugin. Not a satis issue.
